# Namespace
kind: Namespace
apiVersion: v1
metadata:
  name: k8s-demo
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-reader
  namespace: k8s-demo
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: k8s-demo
  name: namespace-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-reader-binding
  namespace: k8s-demo
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""
subjects:
  - kind: ServiceAccount
    name: config-reader
    namespace: k8s-demo
